<a href="https://colab.research.google.com/github/Pritush09/Deeplearning-Tensorflow/blob/master/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb

In [ ]:
# press ctrl + shift + space to see the suggestion of the parameters inside the function
scalar = tf.constant([[7,3,4],
                      [2,1,3]])

In [ ]:
scalar.ndim

2

In [ ]:
scalar.shape

TensorShape([2, 3])

In [ ]:
changable= tf.Variable([3,3])
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3], dtype=int32)>

In [ ]:
changable[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [9]:
# random tensor
ran1 =  tf.random.Generator.from_seed(42) # the seed is for the reproducibility
ran1 = ran1.normal(shape=(3,2)) # it is of the normal form
ran1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [10]:
ran2 =  tf.random.Generator.from_seed(42) # the seed is for the reproducibility
ran2 = ran2.normal(shape=(3,2)) # it is of the normal form
ran2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
# shuffle the tensor
# so to feed the NN by mixed up photos of different foods
shuffle = tf.constant([[7,3,4],
                      [2,1,3],
                      [1,1,2],
                      [22,2,3]])
shuffle

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  3,  4],
       [ 2,  1,  3],
       [ 1,  1,  2],
       [22,  2,  3]], dtype=int32)>

In [13]:
tf.random.shuffle(value=shuffle)
# this shuffle the data on the basis of the first dimension without hampering the second one

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[22,  2,  3],
       [ 2,  1,  3],
       [ 7,  3,  4],
       [ 1,  1,  2]], dtype=int32)>

In [20]:
# what will happen if we use seed
tf.random.set_seed(4)
# after seting the seed the changes are the same
tf.random.shuffle(value=shuffle) # if we only use seed in the arg of this function then it will have ho effect 

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[22,  2,  3],
       [ 7,  3,  4],
       [ 2,  1,  3],
       [ 1,  1,  2]], dtype=int32)>

**LINK** : https://www.tensorflow.org/api_docs/python/tf/random/set_seed
TO refer